spring:
  application:
    name: sharding-jdbc
  shardingsphere:
    datasource:
      names: db-user,db-order
      db-user:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.112.128:3316/db_user?characterEncoding=utf-8&useSSL=false
        username: root
        password: 123
      db-order:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.112.128:3317/db_order?characterEncoding=utf-8&useSSL=false
        username: root
        password: 123


    #读写分离配置规则
    rules:
      sharding:
        tables:
          t_user:
            actual-data-nodes: db-user.t_user
          t_order:
            actual-data-nodes: db-order.t_order

    #打印Sql语句
    props:
      sql-show: true
