spring:
  application:
    name: sharding-jdbc
  shardingsphere:
    datasource:
      names: db-user,db-order0,db-order1
      db-user:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.112.128:3316/db_user?characterEncoding=utf-8&useSSL=false
        username: root
        password: 123
      db-order0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.112.128:3317/db_order?characterEncoding=utf-8&useSSL=false
        username: root
        password: 123
      db-order1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.112.128:3318/db_order?characterEncoding=utf-8&useSSL=false
        username: root
        password: 123
    #读写分离配置规则
    rules:
      sharding:
        tables:
          t_dict:
            actual-data-nodes: db-user.t_dict,db-order${0..1}.t_dict
        broadcast-tables:
          - t_dict


    #打印Sql语句
    props:
      sql-show: true
